service: api-example

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AUTHSIGNAL_SECRET: ${env:AUTHSIGNAL_SECRET}
    AUTHSIGNAL_URL: ${env:AUTHSIGNAL_URL}
    AUTHSIGNAL_TENANT: ${env:AUTHSIGNAL_TENANT}
    AUTHSIGNAL_CLIENT: ${env:AUTHSIGNAL_CLIENT}
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.authorization
        issuerUrl: ${env:AUTHSIGNAL_URL}/client/public/${env:AUTHSIGNAL_TENANT}
        audience:
          - ${env:AUTHSIGNAL_CLIENT}
      requestAuthorizer1:
        type: request
        identitySource: $request.header.authorization
        functionName: requestAuthorizer1
        enableSimpleResponses: true
      requestAuthorizer2:
        type: request
        identitySource: $request.header.authorization
        functionName: requestAuthorizer1
        enableSimpleResponses: true

package:
  individually: true

functions:
  initEmailSignIn:
    handler: api/init-email-sign-in.handler
    events:
      - httpApi:
          method: post
          path: /sign-in/email

  signIn:
    handler: api/sign-in.handler
    events:
      - httpApi:
          method: post
          path: /sign-in

  signOut:
    handler: api/sign-out.handler
    events:
      - httpApi:
          method: post
          path: /sign-out

  refreshSession:
    handler: api/refresh-session.handler
    events:
      - httpApi:
          method: post
          path: /sign-in/refresh

  initPasskeyRegistration:
    handler: api/init-passkey-registration.handler
    events:
      - httpApi:
          method: post
          path: /register/passkey
          authorizer:
            name: requestAuthorizer1

  userProfile:
    handler: api/user-profile.handler
    events:
      - httpApi:
          method: get
          path: /profile
          authorizer:
            name: requestAuthorizer2

  userAuthenticators:
    handler: api/user-authenticators.handler
    events:
      - httpApi:
          method: get
          path: /authenticators
          authorizer:
            name: jwtAuthorizer

  requestAuthorizer1:
    handler: auth/request-authorizer-1.handler

  requestAuthorizer2:
    handler: auth/request-authorizer-2.handler
